//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_SelectParty_Result
    {
        public int party_id { get; set; }
        public string party_name { get; set; }
        public string party_address { get; set; }
        public string contact_no { get; set; }
        public string gstin_no { get; set; }
        public string party_type { get; set; }
        public Nullable<int> state_id { get; set; }
        public string state_name { get; set; }
    }
}
