//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class spAuthenticateUserRole_Result
    {
        public Nullable<int> company_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string role_name { get; set; }
        public string Name { get; set; }
    }
}
