//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class CommonReport_Result
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_address { get; set; }
        public string batch_name { get; set; }
        public int batch_id { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
