//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class Sp_InsertResetPass_Result
    {
        public string username { get; set; }
        public int user_id { get; set; }
        public string uniqueidentifier { get; set; }
        public Nullable<bool> status { get; set; }
        public int Passverify_ID { get; set; }
    }
}
