//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class ProductReport_Result
    {
        public int product_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> godown_id { get; set; }
        public Nullable<int> rack_id { get; set; }
        public Nullable<int> tax_id { get; set; }
        public Nullable<decimal> purchas_price { get; set; }
        public Nullable<decimal> sales_price { get; set; }
        public Nullable<int> reorder_level { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public string hsn_code { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
