//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_SelectTaxpercent_Result
    {
        public Nullable<int> tax_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public string unit_name { get; set; }
        public Nullable<int> batch_id { get; set; }
        public string batch_name { get; set; }
    }
}
