//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_SelectPrice_Result
    {
        public Nullable<decimal> purchas_price { get; set; }
        public Nullable<decimal> sales_price { get; set; }
    }
}
