//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_dashboarddata_Result
    {
        public Nullable<int> TotalPurchaseOrder { get; set; }
        public Nullable<decimal> TotalAmountofPurchase { get; set; }
    }
}
