//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_SelectPurchaseinvoice_Result
    {
        public int purchase_id { get; set; }
        public Nullable<int> party_id { get; set; }
        public string po_no { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public string Date { get; set; }
        public string party_name { get; set; }
    }
}
