//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_SelectRack_Result
    {
        public Nullable<int> rack_id { get; set; }
        public string rack_name { get; set; }
        public string godown_name { get; set; }
        public Nullable<int> godown_id { get; set; }
    }
}
