//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    
    public partial class sp_SelectCompany_Result
    {
        public string company_name { get; set; }
        public string company_address { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public string city { get; set; }
        public string telephone_no { get; set; }
        public string fax_no { get; set; }
        public string pincode { get; set; }
        public string GSTIN { get; set; }
        public string website { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string owner_emailid { get; set; }
        public string owner_mobileno { get; set; }
        public string country_name { get; set; }
        public string state_name { get; set; }
    }
}
