//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_paymentmode
    {
        public tbl_paymentmode()
        {
            this.tbl_monytransaction = new HashSet<tbl_monytransaction>();
            this.tbl_purchase = new HashSet<tbl_purchase>();
            this.tbl_purchasereturn = new HashSet<tbl_purchasereturn>();
            this.tbl_sale = new HashSet<tbl_sale>();
            this.tbl_salereturn = new HashSet<tbl_salereturn>();
        }
    
        public int paymentode_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string paymentmode_name { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual tbl_branch tbl_branch { get; set; }
        public virtual tbl_company tbl_company { get; set; }
        public virtual ICollection<tbl_monytransaction> tbl_monytransaction { get; set; }
        public virtual ICollection<tbl_purchase> tbl_purchase { get; set; }
        public virtual ICollection<tbl_purchasereturn> tbl_purchasereturn { get; set; }
        public virtual ICollection<tbl_sale> tbl_sale { get; set; }
        public virtual ICollection<tbl_salereturn> tbl_salereturn { get; set; }
    }
}
