//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchase
    {
        public tbl_purchase()
        {
            this.tbl_ActualPurchaseTaxAndPrice = new HashSet<tbl_ActualPurchaseTaxAndPrice>();
            this.tbl_purchasedetails = new HashSet<tbl_purchasedetails>();
            this.tbl_PurchasePaymentDetials = new HashSet<tbl_PurchasePaymentDetials>();
            this.tbl_purchasereturn = new HashSet<tbl_purchasereturn>();
        }
    
        public int purchase_id { get; set; }
        public Nullable<int> party_id { get; set; }
        public Nullable<int> financialyear_id { get; set; }
        public string po_no { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<System.DateTime> Po_Date { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> PaymentMode_id { get; set; }
    
        public virtual ICollection<tbl_ActualPurchaseTaxAndPrice> tbl_ActualPurchaseTaxAndPrice { get; set; }
        public virtual tbl_branch tbl_branch { get; set; }
        public virtual tbl_branch tbl_branch1 { get; set; }
        public virtual tbl_company tbl_company { get; set; }
        public virtual tbl_company tbl_company1 { get; set; }
        public virtual tbl_financialyear tbl_financialyear { get; set; }
        public virtual tbl_financialyear tbl_financialyear1 { get; set; }
        public virtual tbl_party tbl_party { get; set; }
        public virtual tbl_party tbl_party1 { get; set; }
        public virtual tbl_paymentmode tbl_paymentmode { get; set; }
        public virtual ICollection<tbl_purchasedetails> tbl_purchasedetails { get; set; }
        public virtual ICollection<tbl_PurchasePaymentDetials> tbl_PurchasePaymentDetials { get; set; }
        public virtual ICollection<tbl_purchasereturn> tbl_purchasereturn { get; set; }
    }
}
