//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_taxdetails
    {
        public int taxdetails_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual tbl_taxgroup tbl_taxgroup { get; set; }
        public virtual tbl_taxtype tbl_taxtype { get; set; }
    }
}
