//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_plan
    {
        public tbl_plan()
        {
            this.tbl_subscription = new HashSet<tbl_subscription>();
        }
    
        public int plan_id { get; set; }
        public string plan_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual ICollection<tbl_subscription> tbl_subscription { get; set; }
    }
}
