//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBLL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subscription
    {
        public tbl_subscription()
        {
            this.tbl_paidpayment = new HashSet<tbl_paidpayment>();
        }
    
        public int subscription_id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual tbl_company tbl_company { get; set; }
        public virtual ICollection<tbl_paidpayment> tbl_paidpayment { get; set; }
        public virtual tbl_plan tbl_plan { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
